import os
import sys
import matplotlib.pyplot as plt

# Add src to path so we can import modules if running from root
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from src.audio_processor import process_audio_file
from src.visualizer import plot_spectrograms

def main():
    # Define paths
    PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DATASET_DIR = os.path.join(PROJECT_ROOT, "datasets", "IRMAS-TrainingData")
    OUTPUT_DIR = os.path.join(PROJECT_ROOT, "outputs")
    
    # Ensure output directory exists
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    # Test file
    # Using a specific file known to exist from previous steps or exploration
    test_file_rel_path = os.path.join("cel", "[cel][cla]0001__1.wav")
    test_file_path = os.path.join(DATASET_DIR, test_file_rel_path)
    
    print(f"--- Starting Pipeline ---")
    print(f"Target File: {test_file_path}")
    
    if not os.path.exists(test_file_path):
        print(f"Error: Test file not found at {test_file_path}")
        return

    # Step 1: Process Audio
    # target_sr=16000 as decided in Task 1
    y, sr = process_audio_file(test_file_path, target_sr=16000)
    
    if y is None:
        print("Audio processing failed.")
        return

    # Save the Waveform (generated by process_audio_file)
    waveform_path = os.path.join(OUTPUT_DIR, f"waveform_{os.path.basename(test_file_path)}.png")
    plt.savefig(waveform_path, dpi=300)
    plt.close()
    print(f"  - Waveform plot saved to {waveform_path}")

    # Step 2: Visualize
    file_name = os.path.basename(test_file_path)
    plot_spectrograms(y, sr, file_name, OUTPUT_DIR)
    
    print("--- Pipeline Completed ---")

if __name__ == "__main__":
    main()
